### ISSUE TITLE
What is the DEM data source？

### ISSUE THREAD

**Issue by SPL724** [slutske22/leaflet-topography#7]
I want to know which data source this DEM uses and what is the resolution.

**Comment by slutske22** [comment]
As stated in the docs, this plugin uses [Mapbox Terrain-RGB](https://docs.mapbox.com/help/getting-started/mapbox-data/#mapbox-terrain-rgb) by default, though it can be configured to use whatever DEM tiles you want.  You'll have to look at the mapbox docs for more info on the data sources for their rgb dem tiles.  As far as resolution goes, I'm not sure what you mean, but the tiles used by default for this plugin are 256x256 (as opposed to the 512x512 double large tiles that have become populat recently).
